url: https://richlogan.github.io
baseurl: /Rockport-Website/

# Site settings
title: Rockport Software
email: info@rockportsoft.com
description: "Enabling the Intelligent Enterprise"


# Social networks usernames
social:
  - title: twitter
    url: http://twitter.com/rockportsoft


# Postal address 
address:
  - line: 126 Fairlie Road
  - line: Slough
  - line: Berkshire
  - line: SL1 4PY
  - line: UK
  - line: tel +44 (0) 1753 577201

# Build settings
markdown: kramdown
permalink: pretty
